version: '3'
services:
  nginx:
    image: nginx
    container_name: 'balancemsql'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '4020:4020'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - proxysql
    networks:
      - backend

  proxysql:
    image: proxysql/proxysql
    ports:
      - 6033:6033
      - 6032:6032
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    networks:
      - backend

  bdm1:
    image: mysql/mysql-server:8.0
    container_name: 'bdm1'
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=banco_de_dados
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    volumes:
      - ./bdm1:/var/lib/mysql
    networks:
      - backend

  bdm2:
    image: mysql/mysql-server:8.0
    container_name: 'bdm2'
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=banco_de_dados
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    volumes:
      - ./bdm2:/var/lib/mysql
    networks:
      - backend

  bdm3:
    image: mysql/mysql-server:8.0
    container_name: 'bdm3'
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=banco_de_dados
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    volumes:
      - ./bdm3:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
